package dev.toma.pubgmc.init;

import dev.toma.pubgmc.Pubgmc;
import dev.toma.pubgmc.common.items.ItemExplodeable;
import dev.toma.pubgmc.common.items.attachment.*;
import dev.toma.pubgmc.common.items.equipment.ItemBackpack;
import dev.toma.pubgmc.common.items.equipment.ItemNVGoggles;
import dev.toma.pubgmc.common.items.guns.FlareGun;
import dev.toma.pubgmc.common.items.guns.GunBase;
import dev.toma.pubgmc.common.items.heal.*;
import net.minecraft.item.Item;
import net.minecraftforge.fml.common.registry.GameRegistry;

@GameRegistry.ObjectHolder(Pubgmc.MOD_ID)
public final class PMCItems {
    public static final ItemBackpack SMALL_BACKPACK_FOREST = null;
    public static final ItemBackpack SMALL_BACKPACK_DESERT = null;
    public static final ItemBackpack SMALL_BACKPACK_SNOW = null;
    public static final ItemBackpack MEDIUM_BACKPACK_FOREST = null;
    public static final ItemBackpack MEDIUM_BACKPACK_DESERT = null;
    public static final ItemBackpack MEDIUM_BACKPACK_SNOW = null;
    public static final ItemBackpack LARGE_BACKPACK_FOREST = null;
    public static final ItemBackpack LARGE_BACKPACK_DESERT = null;
    public static final ItemBackpack LARGE_BACKPACK_SNOW = null;
    public static final ItemBandage BANDAGE = null;
    public static final ItemFirstAidKit FIRSTAIDKIT = null;
    public static final ItemMedkit MEDKIT = null;
    public static final ItemEnergyDrink ENERGYDRINK = null;
    public static final ItemPainkiller PAINKILLERS = null;
    public static final ItemAdrenalineSyringe ADRENALINESYRINGE = null;
    public static final Item GHILLIE_SUIT = null;
    public static final ItemNVGoggles NV_GOGGLES = null;
    public static final FlareGun FLARE_GUN = null;
    public static final GunBase P92 = null;
    public static final GunBase P1911 = null;
    public static final GunBase R1895 = null;
    public static final GunBase R45 = null;
    public static final GunBase P18C = null;
    public static final GunBase SCORPION = null;
    public static final GunBase DEAGLE = null;
    public static final GunBase WIN94 = null;
    public static final GunBase SAWED_OFF = null;
    public static final GunBase S1897 = null;
    public static final GunBase S686 = null;
    public static final GunBase S12K = null;
    public static final GunBase MICROUZI = null;
    public static final GunBase UMP45 = null;
    public static final GunBase VECTOR = null;
    public static final GunBase TOMMY_GUN = null;
    public static final GunBase BIZON = null;
    public static final GunBase MP5K = null;
    public static final GunBase M16A4 = null;
    public static final GunBase M416 = null;
    public static final GunBase SCAR_L = null;
    public static final GunBase G36C = null;
    public static final GunBase QBZ = null;
    public static final GunBase AUG = null;
    public static final GunBase AKM = null;
    public static final GunBase BERYL_M762 = null;
    public static final GunBase MK47_MUTANT = null;
    public static final GunBase GROZA = null;
    public static final GunBase DP28 = null;
    public static final GunBase M249 = null;
    public static final GunBase VSS = null;
    public static final GunBase MINI14 = null;
    public static final GunBase QBU = null;
    public static final GunBase SKS = null;
    public static final GunBase SLR = null;
    public static final GunBase MK14 = null;
    public static final GunBase KAR98K = null;
    public static final GunBase M24 = null;
    public static final GunBase AWM = null;
    public static final ItemExplodeable GRENADE = null;
    public static final ItemExplodeable SMOKE = null;
    public static final ItemExplodeable MOLOTOV = null;
    public static final ItemExplodeable FLASHBANG = null;
    public static final Item AMMO_9MM = null;
    public static final Item AMMO_45ACP = null;
    public static final Item AMMO_SHOTGUN = null;
    public static final Item AMMO_556 = null;
    public static final Item AMMO_762 = null;
    public static final Item AMMO_300M = null;
    public static final Item AMMO_FLARE = null;
    public static final Item ARMOR1HELMET = null;
    public static final Item ARMOR1BODY = null;
    public static final Item ARMOR2HELMET = null;
    public static final Item ARMOR2BODY = null;
    public static final Item ARMOR3HELMET = null;
    public static final Item ARMOR3BODY = null;
    public static final ItemMuzzle SILENCER_SMG = null;
    public static final ItemMuzzle SILENCER_AR = null;
    public static final ItemMuzzle SILENCER_SNIPER = null;
    public static final ItemMuzzle COMPENSATOR_SMG = null;
    public static final ItemMuzzle COMPENSATOR_AR = null;
    public static final ItemMuzzle COMPENSATOR_SNIPER = null;
    public static final ItemScope RED_DOT = null;
    public static final ItemScope HOLOGRAPHIC = null;
    public static final ItemScope SCOPE2X = null;
    public static final ItemScope SCOPE4X = null;
    public static final ItemScope SCOPE8X = null;
    public static final ItemScope SCOPE15X = null;
    public static final ItemGrip GRIP_VERTICAL = null;
    public static final ItemGrip GRIP_ANGLED = null;
    public static final ItemMagazine QUICKDRAW_MAG_SMG = null;
    public static final ItemMagazine EXTENDED_MAG_SMG = null;
    public static final ItemMagazine EXTENDED_QUICKDRAW_MAG_SMG = null;
    public static final ItemMagazine QUICKDRAW_MAG_AR = null;
    public static final ItemMagazine EXTENDED_MAG_AR = null;
    public static final ItemMagazine EXTENDED_QUICKDRAW_MAG_AR = null;
    public static final ItemMagazine QUICKDRAW_MAG_SNIPER = null;
    public static final ItemMagazine EXTENDED_MAG_SNIPER = null;
    public static final ItemMagazine EXTENDED_QUICKDRAW_MAG_SNIPER = null;
    public static final ItemStock BULLET_LOOPS = null;
    public static final ItemStock CHEEKPAD = null;
    public static final Item PARACHUTE = null;
    public static final Item STEEL_DUST = null;
    public static final Item STEEL_INGOT = null;
    public static final Item COPPER_INGOT = null;
    public static final Item FUELCAN = null;
    public static final Item VEHICLE_UAZ = null;
    public static final Item VEHICLE_DACIA = null;
    public static final Item PAN = null;
    public static final Item MACHETE = null;
    public static final Item CROWBAR = null;
    public static final Item SICKLE = null;
}
